threshold: 1
threshold_angle: 1
wp:
  /px4_1:
    - { x: 0, y: 4, z: -5, yaw: 0 }
    - { x: 1.5308, y: 3.6956, z: -15, yaw: 0 }
    - { x: 2.8284, y: 2.8284, z: -15, yaw: 0 }
    - { x: 3.6956, y: 1.5308, z: -15, yaw: 0 }
    - { x: 4, y: 0, z: -5, yaw: 0 }
    - { x: 3.6956, y: -1.5308, z: -5, yaw: 0 }
    - { x: 2.8284, y: -2.8284, z: -5, yaw: 0 }
    - { x: 1.5308, y: -3.6956, z: -5, yaw: 0 }
    - { x: 0, y: -4, z: -10, yaw: 0 }
    - { x: -1.5308, y: -3.6956, z: -5, yaw: 0 }
    - { x: -2.8284, y: -2.8284, z: -5, yaw: 0 }
    - { x: -3.6956, y: -1.5308, z: -5, yaw: 0 }
    - { x: -4, y: 0, z: -5, yaw: 0 }
    - { x: -3.6956, y: 1.5308, z: -5, yaw: 0 }
    - { x: -2.8284, y: 2.8284, z: -2, yaw: 0 }
    - { x: -1.5308, y: 3.6956, z: -0, yaw: 0 }
  # /px4_2:
  #   - { x: 0, y: 4, z: -5, yaw: 0 }
  #   - { x: 1.5308, y: 3.6956, z: -5, yaw: 0 }
  #   - { x: 2.8284, y: 2.8284, z: -5, yaw: 0 }
  #   - { x: 3.6956, y: 1.5308, z: -5, yaw: 0 }
  #   - { x: 4, y: 0, z: -5, yaw: 0 }
  #   - { x: 3.6956, y: -1.5308, z: -5, yaw: 0 }
  #   - { x: 2.8284, y: -2.8284, z: -5, yaw: 0 }
  #   - { x: 1.5308, y: -3.6956, z: -5, yaw: 0 }
  #   - { x: 0, y: -4, z: -10, yaw: 0 }
  #   - { x: -1.5308, y: -3.6956, z: -5, yaw: 0 }
  #   - { x: -2.8284, y: -2.8284, z: -5, yaw: 0 }
  #   - { x: -3.6956, y: -1.5308, z: -5, yaw: 0 }
  #   - { x: -4, y: 0, z: -5, yaw: 0 }
  #   - { x: -3.6956, y: 1.5308, z: -5, yaw: 0 }
  #   - { x: -2.8284, y: 2.8284, z: -5, yaw: 0 }
  #   - { x: -1.5308, y: 3.6956, z: -5, yaw: 0 }
  # /px4_3:
  #   - { x: 0, y: 4, z: -5, yaw: 0 }
  #   - { x: 1.5308, y: 3.6956, z: -5, yaw: 0 }
  #   - { x: 2.8284, y: 2.8284, z: -5, yaw: 0 }
  #   - { x: 3.6956, y: 1.5308, z: -5, yaw: 0 }
  #   - { x: 4, y: 0, z: -5, yaw: 0 }
  #   - { x: 3.6956, y: -1.5308, z: -5, yaw: 0 }
  #   - { x: 2.8284, y: -2.8284, z: -5, yaw: 0 }
  #   - { x: 1.5308, y: -3.6956, z: -5, yaw: 0 }
  #   - { x: 0, y: -4, z: -10, yaw: 0 }
  #   - { x: -1.5308, y: -3.6956, z: -5, yaw: 0 }
  #   - { x: -2.8284, y: -2.8284, z: -5, yaw: 0 }
  #   - { x: -3.6956, y: -1.5308, z: -5, yaw: 0 }
  #   - { x: -4, y: 0, z: -5, yaw: 0 }
  #   - { x: -3.6956, y: 1.5308, z: -5, yaw: 0 }
  #   - { x: -2.8284, y: 2.8284, z: -5, yaw: 0 }
  #   - { x: -1.5308, y: 3.6956, z: -5, yaw: 0 }