threshold: 0.7
threshold_angle: 0.7
wp:
  /px4_1:
    - { x: 0, y: 0, z: -5, yaw: 0 }
    - { x: 10, y: 0, z: -5, yaw: 0 }


# threshold: 0.7
# threshold_angle: 0.7 # 75% of Ï€/4 radians (0.785), i.e., 0.785 * 0.75 = 0.314
# # Coordinates are in the North-East-Down frame x -> y and y -> x
# wp:
#   /px4_1:
#     # Full Circle with 36 waypoints (10 degrees each)
#     - { x: 4.0000, y: 0.0000, z: -5, yaw: 0 }
#     - { x: 3.9380, y: 0.6946, z: -5, yaw: 0 }
#     - { x: 3.7570, y: 1.3778, z: -5, yaw: 0 }
#     - { x: 3.4641, y: 2.0000, z: -5, yaw: 0 }
#     - { x: 3.0711, y: 2.6180, z: -5, yaw: 0 }
#     - { x: 2.5850, y: 3.1962, z: -5, yaw: 0 }
#     - { x: 2.0000, y: 3.4641, z: -5, yaw: 0 }
#     - { x: 1.3778, y: 3.7570, z: -5, yaw: 0 }
#     - { x: 0.6946, y: 3.9380, z: -5, yaw: 0 }
#     - { x: 0.0000, y: 4.0000, z: -5, yaw: 0 }
#     - { x: -0.6946, y: 3.9380, z: -5, yaw: 0 }
#     - { x: -1.3778, y: 3.7570, z: -5, yaw: 0 }
#     - { x: -2.0000, y: 3.4641, z: -5, yaw: 0 }
#     - { x: -2.5850, y: 3.1962, z: -5, yaw: 0 }
#     - { x: -3.0711, y: 2.6180, z: -5, yaw: 0 }
#     - { x: -3.4641, y: 2.0000, z: -5, yaw: 0 }
#     - { x: -3.7570, y: 1.3778, z: -5, yaw: 0 }
#     - { x: -3.9380, y: 0.6946, z: -5, yaw: 0 }
#     - { x: -4.0000, y: 0.0000, z: -5, yaw: 0 }
#     - { x: -3.9380, y: -0.6946, z: -5, yaw: 0 }
#     - { x: -3.7570, y: -1.3778, z: -5, yaw: 0 }
#     - { x: -3.4641, y: -2.0000, z: -5, yaw: 0 }
#     - { x: -3.0711, y: -2.6180, z: -5, yaw: 0 }
#     - { x: -2.5850, y: -3.1962, z: -5, yaw: 0 }
#     - { x: -2.0000, y: -3.4641, z: -5, yaw: 0 }
#     - { x: -1.3778, y: -3.7570, z: -5, yaw: 0 }
#     - { x: -0.6946, y: -3.9380, z: -5, yaw: 0 }
#     - { x: 0.0000, y: -4.0000, z: -5, yaw: 0 }
#     - { x: 0.6946, y: -3.9380, z: -5, yaw: 0 }
#     - { x: 1.3778, y: -3.7570, z: -5, yaw: 0 }
#     - { x: 2.0000, y: -3.4641, z: -5, yaw: 0 }
#     - { x: 2.5850, y: -3.1962, z: -5, yaw: 0 }
#     - { x: 3.0711, y: -2.6180, z: -5, yaw: 0 }
#     - { x: 3.4641, y: -2.0000, z: -5, yaw: 0 }
#     - { x: 3.7570, y: -1.3778, z: -5, yaw: 0 }
#     - { x: 3.9380, y: -0.6946, z: -5, yaw: 0 }

